"""Aumenta tamanho das colunas de cliente

Revision ID: 2bff06478ebf
Revises: 55b8f2895431
Create Date: 2025-10-17 22:44:19.362830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bff06478ebf'
down_revision = '55b8f2895431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=14),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.alter_column('conta',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('tipo_conta',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=19),
               existing_nullable=False)
        batch_op.alter_column('bandeira_cartao_credito',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('cartao_debito',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=19),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('cartao_debito',
               existing_type=sa.String(length=19),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('bandeira_cartao_credito',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.alter_column('tipo_conta',
               existing_type=sa.String(length=19),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('conta',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
