"""Cria a tabela inicial de clientes

Revision ID: 50b7b7c84064
Revises: 2bff06478ebf
Create Date: 2025-10-19 01:46:42.537811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b7b7c84064'
down_revision = '2bff06478ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('agencia', sa.String(length=10), nullable=False),
    sa.Column('conta', sa.String(length=10), nullable=False),
    sa.Column('tipo_conta', sa.String(length=19), nullable=False),
    sa.Column('cartao_credito', sa.String(length=20), nullable=True),
    sa.Column('bandeira_cartao_credito', sa.String(length=20), nullable=True),
    sa.Column('cartao_debito', sa.String(length=19), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
